### ISSUE TITLE
suggestion itemModel not resolved

### ISSUE THREAD

**Issue by abalta** [mars885/persistent-search-view#12]
I want to use OnSuggestionChangeListener, but itemModel not resolved. I'm getting following error.

Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.paulrybitskyi.persistentsearchview.adapters.model.SuggestionItem, unresolved supertypes: com.arthurivanets.adapster.model.BaseItem, com.arthurivanets.adapster.model.markers.Trackable

**Comment by mars885** [comment]
Have you tried cleaning and then rebuilding project or, alternatively, invalidating caches and then restarting the project?

**Comment by abalta-mobven** [comment]
I tried everything. Nothing works. But, I added arthurivanets' library in my gradle it works. Why I need to add another library. Please, create an empty project add your library via gradle.

**Comment by pavloselpidorou** [comment]
same issue here. itemModel not resolved

**Comment by pavloselpidorou** [comment]
I resolved this issue with including com.arthurivanets.adapster:adapster library

**Comment by mars885** [comment]
I've just tested the library by creating a new project and then including the library. Everything seems to be working fine for me. Looks like this issue happens only for very small subset of users.

**Comment by gowthamgts** [comment]
same issue here.

**Comment by FFSDevelopers** [comment]
Resolved by adding implementation "com.arthurivanets.adapster:adapster:1.0.13".

**Comment by FFSDevelopers** [comment]
Resolved by adding implementation "com.arthurivanets.adapster:adapster:1.0.13".

**Comment by guyijie1211** [comment]
same issue

> implementation "com.arthurivanets.adapster:adapster:1.0.13"

solved, Thanks
