### ISSUE TITLE
Binary XML file line #29: Binary XML file line #29: Error inflating class com.paulrybitskyi.persistentsearchview.PersistentSearchView

### ISSUE THREAD

**Issue by mustafayildizz** [mars885/persistent-search-view#15]
When I tried to implement library, at the beginning get this error. Is there anyone know the reason?

**Comment by mars885** [comment]
@mustafayildizz Could you post the full stack trace of the error? Would help a lot to pin down the issue.

**Comment by mustafayildizz** [comment]
Thank you and sorry for late answer. No longer needed. Thanks a lot again.
