### ISSUE TITLE
Button to set suggestion text as query

### ISSUE THREAD

**Issue by trung39** [mars885/persistent-search-view#17]
Hello author. I'm intergrating this search view to my app and it's an amazing search view.

I would like to suggest to have this button at the right of Regular Suggestion view. It will set the suggestion text as the query and also call the OnSearchQueryChangeListener.

Below is an image of Google app as example
![image](https://user-images.githubusercontent.com/25921836/105953264-77295580-60a5-11eb-82e3-b7cf8f0ba09d.png)

Thank you.

**Comment by mars885** [comment]
Hello there.

This is a nice suggestion. Unfortunately, I've been overwhelmed by work recently and do not have to time to implement it.

Pull requests are welcome though. Just make sure to follow the code's styling, give descriptive names, update the sample, etc.

**Comment by trung39** [comment]
Thank you. I will make a pull request if I have time.
