### ISSUE TITLE
jcenter deprecation

### ISSUE THREAD

**Issue by gowthamgts** [mars885/persistent-search-view#18]
Hello, since jcenter will be deprecated soon enough, any plans to release this via mavencentral?

**Comment by mars885** [comment]
Hello there.

I'm planning to migrate the lib to the Maven Central in the next week.

Stay tuned.

**Comment by gowthamgts** [comment]
thank you!

**Comment by mars885** [comment]
See #19.

**Comment by gowthamgts** [comment]
Thank you!
