### ISSUE TITLE
Gradle build error while removing jcenter

### ISSUE THREAD

**Issue by yenaingoo992** [mars885/persistent-search-view#34]
I have got 'Could not find com.arthurivanets.adapster:adapster:1.0.13.' error message while removing jcenter in build.gradle as suggested in android studio.

**Comment by jja08111** [comment]
same issue

**Comment by tomleejumah** [comment]
add
 jcenter()
        maven { url 'https://jitpack.io' }
in your settings.graddle

**Comment by mars885** [comment]
Hey.

The solution is to declare `jcenter()` repository to your project as of now.
