### ISSUE TITLE
Your own given sample has missing classes.

### ISSUE THREAD

**Issue by VirajShirwalkar** [mars885/persistent-search-view#43]
![image](https://user-images.githubusercontent.com/75793707/200560981-8f38f590-f0db-4cad-9764-ed884a981e81.png)

Unable to do UI changes in XML file where your searchview is added. 
Please fi asap.

**Comment by mars885** [comment]
Hey.

Is this still relevant?

**Comment by VirajShirwalkar** [comment]
Hi
Please close for now. We will try some time again.
