### ISSUE TITLE
Unable to add library to app.

### ISSUE THREAD

**Issue by n1snt** [mars885/persistent-search-view#44]
When I try to add this library to my app I'm greeted with the following error:
```
Failed to resolve: com.arthurivanets.adapster:adapster:1.0.13
Show in Project Structure dialog
Affected Modules: app
```

**Comment by alam-faiz** [comment]
same issue with me, can you please suggest what can we do to resolve the issue

**Comment by mars885** [comment]
Hey.

The only solution to this problem is to declare `jcenter()` in the list of repositories because of the `adapster` dependency that is available only on the JCenter.
